[package]
name = "allfarbe"
version = "0.1.0"
authors = ["Luis Hoderlein <lrh74@cornell.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

exclude = [
    ".github/previews/*"
]

[dependencies]
glium = "*"
noise = "0.6.0"